### PR TITLE
Circular dependencies

### PR DESCRIPTION
**Pull request by vf-telwing**
## Description

Use Symbols as unique identifiers for `BaseMenu` and `BaseMenuToggle` to avoid circular dependencies when validating object types.

## Related Issues

https://github.com/NickDJM/accessible-menu/issues/95

### CODE REVIEW

**Comment by NickDJM** [comment]
@vf-telwing Thanks! I'll take a look at this shortly and hopefully get it merged in to `next`.

**Comment by vf-telwing** [comment]
@NickDJM Thank you! Sorry about the messy commits, sometimes Git and I don't get along...

**Comment by NickDJM** [comment]
@vf-telwing no worries, that's what commit squashing is for!

**Comment by NickDJM** [comment]
Everything looks good code-wise.

I've tested on Chrome/FF/Edge

I'm currently not on a machine that can run either IE or Safari, so I'll test those browsers later and if it all goes well then this will be ready to merge!

**Comment by vf-telwing** [comment]
Awesome, let me know if you need anything else.

**Comment by NickDJM** [comment]
Getting back to this and everything works as expected in IE/Safari. Merging

**Review by NickDJM — APPROVED** [review]

**Pull request merged**
