### PR TITLE
docs: correct links for WAI ARIA examples

### PR DESCRIPTION
**Pull request by mandrasch**
Hope I got the ones right, looked them up via https://www.w3.org/TR/wai-aria-practices-1.2/examples/

### CODE REVIEW

**Comment by NickDJM** [comment]
@mandrasch Can you make sure your commit meets the guidelines? https://github.com/NickDJM/accessible-menu/blob/8516528e80cef9d97264599b17b25fe860665f2e/.github/CONTRIBUTING.md#commit-guidelines

Otherwise this looks good.

**Comment by mandrasch** [comment]
You mean commit title "docs: correct links for WAI ARIA examples"?

**Comment by NickDJM** [comment]
No, the actual commit needs to follow the standard otherwise it doesn't get caught in the changelogs.

If you run a `git commit --amend` you can change the message and then push it up.

There's a hook that will lint the commit message to make sure it follows the standard if you run `npm install`.

**Comment by mandrasch** [comment]
> No, the actual commit needs to follow the standard otherwise it doesn't get caught in the changelogs.
> 
> If you run a `git commit --amend` you can change the message and then push it up.
> 
> There's a hook that will lint the commit message to make sure it follows the standard if you run `npm install`.

Ah okay, thanks for explaining! Just did it quickly with GitHub online editor. I'll submit a new PR.

**Pull request closed without merging**
