### PR TITLE
Prevent submenus from closing if mouse leaves and re-enters within leaveDelay ms

### LINKED ISSUE #299: Bug: disclosure submenus close unexpectedly when hover is on and mouse leaves and re-enters
## Summary
With a DisclosureMenu with hover on and leaveDelay > 0, if you hover to open a menu, move your mouse cursor outside the menu, and then return the cursor before menu closes, the menu will still close, even with your cursor hovering over it. This behavior is awkward and confusing for users.

## Steps to reproduce
1. Create a DisclosureMenu with settings like:
```
hoverType: 'on',
enterDelay: 0,
leavedelay: 1000
```
2. Hover over a top-level menu item to open the submenu
3. Move your cursor into the submenu
4. Move your cursor out of the submenu, then back in within 1000 ms (as if you accidentally moved it too far, then corrected)
5. The submenu still closes.

## Expected Behaviour
leaveDelay timeout should be cleared on cursor re-entry. Menus should only close when you (a) open another menu, or (b) keep your cursor outside them for leaveDelay ms.

## Additional context
CodePen example, based on the "Disclosure Navigation Menu" example from this repo: https://codepen.io/synthetiv/pen/WNWGqxr

### PR DESCRIPTION
**Pull request by synthetiv**
## Description
This fixes #299, at least for my use case, by storing and clearing the leaveDelay timeout that is set when the user's cursor exits a submenu.

This has not yet been tested with second-level submenus (i.e. sub-submenus).

## Related Issues
#299

### CODE REVIEW

**Comment by NickDJM** [comment]
I've done some manual testing in the demo environment (`npm run dev`).

This fix works well with Disclosure Menus, Menubars, and Treeviews with single and multi-level menus. It does not work for Top Link Disclosure Menus though. Top Link Disclosure Menus overwrite the base `_handleHover()` method, so this will need to be added there as well.

Tests will also need to be updated/added to to check for this case.

**Comment by synthetiv** [comment]
Thank you, Nick! I should have some time to tackle this next week.

**Comment by NickDJM** [comment]
@synthetiv I have some time this week to work on the project. Are you still planning on implementing this fix? Or do you want me to hop on it as well?

**Comment by NickDJM** [comment]
I've been looking into this and I've run into a handful of interesting cases that make this a little bit of a bigger issue than expected.

- Hovering out and then back in to the open menu works fine with this change.
- Hovering out of the menu, in to the menu's toggle causes the menu to close and then reopen (I have this fixed locally, just need to commit).
- Hovering out of the menu in to one of the menu's toggle's siblings that is not a submenu toggle and then back in works fine.
- Hovering out of the menu in to one of the menu's toggle's siblings that _is_ a submenu toggle then back in, closes the menu (I have tried to fix this, but my first attempt broke hover on treeviews, which obviously isn't great).

We'll need to get all those working for all menus and then figure out all the automated tests to write for those... Just a bit more complex than I immediately thought.

**Comment by synthetiv** [comment]
Ah, thanks for picking this thread back up. I've only had time to address this issue for the specific use case where I observed it; back in March I began writing some tests for the other menu types but never got around to finishing them, and it sounds like you've found a few more specific scenarios that need testing.

If/when I do have a moment to dig in further, I will let you know – sorry I haven't so far.

**Comment by NickDJM** [comment]
@synthetiv no worries. I'll be puttering away at this as well (I have a MR against your branch with changes I'm making).

**Comment by NickDJM** [comment]
I was discussing this with a colleague on Friday and we think there might be a need to move the timeout functions to be owned by the toggles themselves. We might need to track which toggle is opening/closing in which case it makes more sense for the toggles to own the events entirely.

I'll need to play around with this a little more though.

**Comment by NickDJM** [comment]
Ok I have it all worked out I think. I moved _hoverTimeout to the menu items. This allows each individual menu item to control it's own timeouts, which looks like it works excellently.

~~Given this is moving a protected field that shouldn't really be used outside of the menu itself, I think this doesn't really warrant a breaking change.~~

This is going to be a breaking change, so it'll need to be a new major.

The following still need to be done:
- [ ] Add documentation for the new hoverTimeout (theres a getter/setter in menuItem now so menus can properly access it).
- [ ] Add tests for the new getter/setters.
- [ ] Add tests for the new interactions for entering/leaving menu items.
  - Mouse enters item, leaves, re-enters item.
  - Mouse enters item, leaves, enters non-submenu sibling, leaves sibling, re-enters item.
  - Mouse enters item, leaves, enters submenu toggle sibling, leaves sibling, re-enters item.
  - Mouse enters item, leaves, enters parent's non-submenu sibling, leaves sibling, re-enters item.
  - Mouse enters item, leaves enters parent's submenu sibling, leaves sibling, re-enters item.

**Comment by NickDJM** [comment]
@synthetiv Are you able to give me commit privileges to your repo? It'll make it easier to run the automated tests.

**Comment by NickDJM** [comment]
Moving all work to #314

**Comment by NickDJM** [comment]
Closing this. I pulled all the changes made here into the other MR and it has been merged.

**Pull request closed without merging**
